# Generated by Django 3.1.7 on 2021-03-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corgiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='dog_pictures',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
