# Generated by Django 3.1.7 on 2021-03-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corgiapp', '0002_auto_20210305_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='dog_pictures',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='dog_breed',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
