# Generated by Django 3.1.7 on 2021-03-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corgiapp', '0003_auto_20210305_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_picture',
            new_name='profile_pictures',
        ),
    ]
