# Generated by Django 3.1.7 on 2021-03-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corgiapp', '0004_auto_20210305_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom1', models.CharField(blank=True, max_length=30)),
                ('symptom2', models.CharField(blank=True, max_length=30)),
                ('symptom3', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
