# Generated by Django 3.1.7 on 2021-03-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corgiapp', '0005_healthcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom1', models.CharField(blank=True, max_length=50)),
                ('symptom2', models.CharField(blank=True, max_length=50)),
                ('symptom3', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HealthCheck',
        ),
    ]
